Storage:
  engine: sqlite
  MySQL:
    user: root
    pass: ''
    port: 3306
    db: minecraft
    host: localhost
Settings:
  Currency:
    SingularName: Coin
    PluralName: Coins
  Accounts:
    StartingAmount: 0
    ServerAccount: Server