name: EtriaEconomy
version: 1.0.0
author: MistPhizzle
main: com.etriacraft.EtriaEconomy.EtriaEconomy
loadbefore: [ChestShop]
commands:
  money:
    aliases: [etriaeconomy, balance, econ]
permissions:
  etriaeconomy.admin:
    default: op
    children:
      etriaeconomy.user: true
      etriaeconomy.create: true
      etriaeconomy.money.give: true
      etriaeconomy.money.take: true
      etriaeconomy.money.delete: true
      etriaeconomy.money.interest.compound: true
  etriaeconomy.user:
    default: op
    children:
      etriaeconomy.balance.other: true
      etriaeconomy.money.top: true
      etriaeconomy.money.send: true
      etriaeconomy.money.interest.info: true